name: Trigger Render Deployment
on:
  push:
    branches:
      - master
jobs:
  main:
    name: Deploy to Render
    runs-on: windows-latest
    steps:
    - name: Trigger deployment
      run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}