name: Deployment pipeline

on: 
    push:
            branches: 
                - master
    
    pull_request:    
      branches: [master]   
      types: [opened, synchronize]
jobs: 
    simple_deployment_pipeline:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '16'
            - name: Install dependencies
              run: npm install

            - name: lint
              run: npm run eslint

            - name: build
              run: npm run build

            - name: test
              run: npm run test
            
            - name: e2e tests
              uses: cypress-io/github-action@v5
              with:
                command: npm run test:e2e
                start: npm run start-prod
                wait-on: http://localhost:5000
    tag_release: 
      name: Bump version and push tag
      runs-on: windows-latest
      needs: simple_deployment_pipeline
      if: ${{ github.event_name == 'push' }}
      steps: 
            - name: Set env SKIP
              run: echo "SKIP=$( echo ${{ contains( join(github.event.commits.*.message), '#skip') }} )" >> $GITHUB_ENV
            - name: Checkout
              uses: actions/checkout@v3
              with:
                ref: ${{ github.event.pull_request.merge_commit_sha }}
                fetch-depth: '0'
            - name: Was there a skip command?
              run: |
                if ($SKIP) {
                Write-Output "#Skip found"
                } else {
                Write-Output "#Skip not found"
                }
            - name: Update version number
              if: env.SKIP != 'true'
              uses: anothrNick/github-tag-action@1.67.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                DEFAULT_BUMP: patch
      
            
    deploy_to_render:        
      runs-on: windows-latest
      needs: simple_deployment_pipeline
      if: ${{ github.event_name == 'push' }}
      steps:
        - name: Trigger deployment
          run: |
            curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}